-- CEYLONIC GEMS: run in Supabase SQL Editor
create extension if not exists pgcrypto;
do $$ begin create type public.user_role as enum ('buyer','seller','both','admin'); exception when duplicate_object then null; end $$;
do $$ begin create type public.verification_status as enum ('not_submitted','pending','verified','rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.gem_status as enum ('draft','payment_pending','pending','changes_requested','published','rejected','reserved','sold','archived'); exception when duplicate_object then null; end $$;

create table if not exists public.profiles(
 id uuid primary key references auth.users(id) on delete cascade,
 role public.user_role not null default 'buyer', display_name text not null,
 citizenship text not null check(citizenship in('sri_lankan','foreign')),
 verification_status public.verification_status not null default 'not_submitted',
 verified_badge boolean not null default false, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.billing_profiles(user_id uuid primary key references public.profiles(id) on delete cascade,phone text not null,address text not null,city text not null,country text not null,updated_at timestamptz not null default now());
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$
begin insert into public.profiles(id,role,display_name,citizenship) values(new.id,coalesce((new.raw_user_meta_data->>'role')::public.user_role,'buyer'),coalesce(nullif(new.raw_user_meta_data->>'display_name',''),'Ceylonic Member'),case when new.raw_user_meta_data->>'citizenship'='foreign' then 'foreign' else 'sri_lankan' end);insert into public.billing_profiles(user_id,phone,address,city,country) values(new.id,coalesce(new.raw_user_meta_data->>'phone',''),coalesce(new.raw_user_meta_data->>'address',''),coalesce(new.raw_user_meta_data->>'city',''),coalesce(nullif(new.raw_user_meta_data->>'country',''),'Sri Lanka'));return new;end;$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create table if not exists public.identity_verifications(
 id uuid primary key default gen_random_uuid(),user_id uuid not null unique references public.profiles(id) on delete cascade,
 document_type text not null check(document_type in('nic_old','nic_new','passport')),document_number_hash text not null unique,
 document_number_last4 text not null,document_front_path text not null,document_back_path text,selfie_path text not null,
 status text not null default 'pending' check(status in('pending','verified','rejected')),admin_note text,
 reviewed_by uuid references public.profiles(id),reviewed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.gems(
 id uuid primary key default gen_random_uuid(),seller_id uuid not null references public.profiles(id) on delete cascade,
 name text not null,gem_type text not null,variety text,origin text,carat numeric(12,3) not null check(carat>0),
 price numeric(18,2) not null check(price>0),currency text not null check(currency ~ '^[A-Z]{3}$'),
 treatment text,clarity text,cut text,color text,dimensions text,description text,cover_image_path text,
 certificate_status text not null default 'not_submitted',availability text not null default 'Available',
 status public.gem_status not null default 'draft',payment_status text not null default 'unpaid' check(payment_status in('unpaid','pending','paid','refunded')),
 listing_fee_lkr numeric(12,2) not null default 500,admin_note text,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now()
);
create table if not exists public.gem_media(id uuid primary key default gen_random_uuid(),gem_id uuid not null references public.gems(id) on delete cascade,owner_id uuid not null references public.profiles(id) on delete cascade,path text not null,media_type text not null check(media_type in('image','video')),sort_order integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.gem_certificates(id uuid primary key default gen_random_uuid(),gem_id uuid not null references public.gems(id) on delete cascade,owner_id uuid not null references public.profiles(id) on delete cascade,path text not null,laboratory text,certificate_number text,status text not null default 'submitted' check(status in('submitted','under_review','verified','unable_to_verify','rejected')),created_at timestamptz not null default now());
create table if not exists public.offers(id uuid primary key default gen_random_uuid(),gem_id uuid not null references public.gems(id) on delete cascade,buyer_id uuid not null references public.profiles(id) on delete cascade,buyer_alias text not null,amount numeric(18,2) not null check(amount>0),currency text not null check(currency ~ '^[A-Z]{3}$'),status text not null default 'active' check(status in('active','withdrawn','accepted','declined','countered')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(gem_id,buyer_id));
create table if not exists public.gem_votes(id uuid primary key default gen_random_uuid(),gem_id uuid not null references public.gems(id) on delete cascade,buyer_id uuid not null references public.profiles(id) on delete cascade,vote smallint not null check(vote in(-1,1)),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(gem_id,buyer_id));
create table if not exists public.appointments(id uuid primary key default gen_random_uuid(),buyer_id uuid not null references public.profiles(id) on delete cascade,gem_id uuid references public.gems(id) on delete set null,appointment_type text not null,preferred_at timestamptz not null,timezone text not null,notes text,status text not null default 'pending' check(status in('pending','approved','rescheduled','cancelled','completed')),assigned_admin uuid references public.profiles(id),created_at timestamptz not null default now());
create table if not exists public.transactions(id uuid primary key default gen_random_uuid(),gem_id uuid not null references public.gems(id),buyer_id uuid not null references public.profiles(id),seller_id uuid not null references public.profiles(id),accepted_offer_id uuid references public.offers(id),amount numeric(18,2) not null,currency text not null,success_fee_percent numeric(5,2) not null default 1,success_fee_amount numeric(18,2) generated always as(amount*success_fee_percent/100) stored,payment_status text not null default 'unpaid',status text not null default 'created',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.payments(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id),purpose text not null check(purpose in('listing_fee','transaction')),reference_id uuid not null,order_id text not null unique,amount numeric(18,2) not null,currency text not null,provider text not null default 'payhere',provider_payment_id text,status text not null default 'pending',provider_payload jsonb,paid_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.audit_logs(id bigint generated always as identity primary key,actor_id uuid references public.profiles(id),action text not null,entity_type text not null,entity_id uuid,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create unique index if not exists transactions_gem_unique on public.transactions(gem_id);
create unique index if not exists transactions_accepted_offer_unique on public.transactions(accepted_offer_id) where accepted_offer_id is not null;
create index if not exists gems_status_idx on public.gems(status,published_at desc);create index if not exists gems_seller_idx on public.gems(seller_id,created_at desc);create index if not exists offers_gem_idx on public.offers(gem_id,amount desc) where status='active';create index if not exists payments_order_idx on public.payments(order_id);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=(select auth.uid()) and role='admin')$$;
create or replace function public.is_verified_buyer() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=(select auth.uid()) and role in('buyer','both') and verification_status='verified')$$;
create or replace function public.is_verified_seller() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.profiles where id=(select auth.uid()) and role in('seller','both') and verification_status='verified')$$;
create or replace function public.get_gem_rating(target_gem uuid) returns table(rating numeric,vote_total bigint,up_votes bigint,down_votes bigint) language sql stable security definer set search_path='' as $$with c as(select count(*)::bigint total,count(*)filter(where vote=1)::bigint ups,count(*)filter(where vote=-1)::bigint downs from public.gem_votes where gem_id=target_gem)select case when total<5 then null else round((1+6*((ups+5.44)/(total+8)))::numeric,1)end,total,ups,downs from c$$;
create or replace view public.gem_public_offers with(security_barrier=true) as select id,gem_id,buyer_alias,amount,currency,created_at from public.offers where status='active';

alter table public.profiles enable row level security;alter table public.billing_profiles enable row level security;alter table public.identity_verifications enable row level security;alter table public.gems enable row level security;alter table public.gem_media enable row level security;alter table public.gem_certificates enable row level security;alter table public.offers enable row level security;alter table public.gem_votes enable row level security;alter table public.appointments enable row level security;alter table public.transactions enable row level security;alter table public.payments enable row level security;alter table public.audit_logs enable row level security;
create policy "safe profiles read" on public.profiles for select using(verified_badge=true or id=(select auth.uid()) or public.is_admin());
create policy "own profile update" on public.profiles for update using(id=(select auth.uid())) with check(id=(select auth.uid()));create policy "billing own read" on public.billing_profiles for select using(user_id=(select auth.uid()) or public.is_admin());create policy "billing own update" on public.billing_profiles for update using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "own verification read" on public.identity_verifications for select using(user_id=(select auth.uid()) or public.is_admin());
create policy "admin verification all" on public.identity_verifications for all using(public.is_admin()) with check(public.is_admin());
create policy "published or own gems read" on public.gems for select using(status='published' or seller_id=(select auth.uid()) or public.is_admin());
create policy "verified seller gem insert" on public.gems for insert with check(seller_id=(select auth.uid()) and public.is_verified_seller() and status='payment_pending' and payment_status='unpaid');
create policy "seller draft update" on public.gems for update using(seller_id=(select auth.uid()) and status<>'published') with check(seller_id=(select auth.uid()));
create policy "admin gems all" on public.gems for all using(public.is_admin()) with check(public.is_admin());
create policy "media read" on public.gem_media for select using(exists(select 1 from public.gems where gems.id=gem_id and gems.status='published') or owner_id=(select auth.uid()) or public.is_admin());
create policy "media insert own" on public.gem_media for insert with check(owner_id=(select auth.uid()) and exists(select 1 from public.gems where gems.id=gem_id and gems.seller_id=(select auth.uid())));create policy "media update own" on public.gem_media for update using(owner_id=(select auth.uid())) with check(owner_id=(select auth.uid()));create policy "media delete own" on public.gem_media for delete using(owner_id=(select auth.uid()));
create policy "certificate read" on public.gem_certificates for select using(owner_id=(select auth.uid()) or public.is_admin());create policy "certificate insert" on public.gem_certificates for insert with check(owner_id=(select auth.uid()) and exists(select 1 from public.gems where gems.id=gem_id and gems.seller_id=(select auth.uid())));create policy "certificate admin" on public.gem_certificates for all using(public.is_admin()) with check(public.is_admin());
create policy "offers read" on public.offers for select using(buyer_id=(select auth.uid()) or exists(select 1 from public.gems where gems.id=gem_id and gems.seller_id=(select auth.uid())) or public.is_admin());create policy "offer insert" on public.offers for insert with check(buyer_id=(select auth.uid()) and public.is_verified_buyer() and status='active');create policy "offer update own" on public.offers for update using(buyer_id=(select auth.uid())) with check(buyer_id=(select auth.uid()));create policy "offer delete own" on public.offers for delete using(buyer_id=(select auth.uid()));
create policy "votes read" on public.gem_votes for select using(true);create policy "vote insert" on public.gem_votes for insert with check(buyer_id=(select auth.uid()) and public.is_verified_buyer());create policy "vote update own" on public.gem_votes for update using(buyer_id=(select auth.uid())) with check(buyer_id=(select auth.uid()));create policy "vote delete own" on public.gem_votes for delete using(buyer_id=(select auth.uid()));
create policy "appointment read" on public.appointments for select using(buyer_id=(select auth.uid()) or public.is_admin());create policy "appointment insert" on public.appointments for insert with check(buyer_id=(select auth.uid()) and status='pending' and assigned_admin is null);create policy "appointment admin" on public.appointments for all using(public.is_admin()) with check(public.is_admin());
create policy "transactions parties" on public.transactions for select using(buyer_id=(select auth.uid()) or seller_id=(select auth.uid()) or public.is_admin());create policy "transactions admin" on public.transactions for all using(public.is_admin()) with check(public.is_admin());
create policy "payments own" on public.payments for select using(user_id=(select auth.uid()) or public.is_admin());create policy "audit admin" on public.audit_logs for select using(public.is_admin());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)values('gem-media','gem-media',true,52428800,array['image/jpeg','image/png','image/webp','video/mp4','video/webm']),('identity-private','identity-private',false,10485760,array['image/jpeg','image/png','application/pdf']),('certificates-private','certificates-private',false,15728640,array['image/jpeg','image/png','application/pdf'])on conflict(id)do nothing;
create policy "public gem files" on storage.objects for select using(bucket_id='gem-media');create policy "own gem upload" on storage.objects for insert to authenticated with check(bucket_id='gem-media' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy "own gem update" on storage.objects for update to authenticated using(bucket_id='gem-media' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy "own gem delete" on storage.objects for delete to authenticated using(bucket_id='gem-media' and(storage.foldername(name))[1]=(select auth.uid())::text);
create policy "own identity upload" on storage.objects for insert to authenticated with check(bucket_id='identity-private' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy "identity private read" on storage.objects for select to authenticated using(bucket_id='identity-private' and((storage.foldername(name))[1]=(select auth.uid())::text or public.is_admin()));
create policy "own certificate upload" on storage.objects for insert to authenticated with check(bucket_id='certificates-private' and(storage.foldername(name))[1]=(select auth.uid())::text);create policy "certificate private read" on storage.objects for select to authenticated using(bucket_id='certificates-private' and((storage.foldername(name))[1]=(select auth.uid())::text or public.is_admin()));
grant select on public.gem_public_offers to anon,authenticated;grant execute on function public.get_gem_rating(uuid) to anon,authenticated;

-- Column-level privilege hardening
revoke update on public.profiles from authenticated;grant update(display_name,updated_at) on public.profiles to authenticated;
revoke update on public.gems from authenticated;grant update(name,gem_type,variety,origin,carat,price,currency,treatment,clarity,cut,color,dimensions,description,cover_image_path,updated_at) on public.gems to authenticated;
revoke update on public.offers from authenticated;grant update(buyer_alias,amount,currency,updated_at) on public.offers to authenticated;
revoke select on public.offers from anon;grant select on public.gem_public_offers to anon,authenticated;
